name : testproject
on : push
env:
  hello : value
  password: ${{secrets.PASSWORD}}
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.publish.outputs.some}}
    steps:
      - name : Get code
        uses : actions/checkout@v3
      - name : cache
        uses : actions/cache@v4
        with :
          path: ~/.npm
          key : deps-${{hashFiles('**/pcakage-lock.json')}}
      - name : install
        run : npm ci
      - name : build
        run : npm run build
      - name : set values
        id  : publish
        run : echo "some=123" >> $GITHUB_OUTPUT
      - name : print 
        run : echo " ${{env.password}}"
      # - name : publish name
      #   run : find .next/build/chunks/ -type f -name "*.js" -exec echo'{}'';'
      - name : artifact upload
        uses : actions/upload-artifact@v4
        with : 
          name: next -files
          path : |
            .next
            package.json
  deploy:
    needs: test
    runs-on : ubuntu-latest
    steps:
      # - name : cache
      #   uses : actions/cache@v4
      #   with :
      #     path: ~/.npm
      #     key : deps-${{hashFiles('**/pcakage-lock.json')}}
      # - name : install ll
      #   run : npm install
      - name : download artifact
        uses : actions/download-artifact@v4
        with:
          name : next -files
      - name : print directoruies
        run : ls
      - name : values
        run : echo "output from ${{needs.test.outputs.file}} "
      - name: copy from previous jobs
        uses: actions/download-artifact@v4
      - name: deploy
        run : echo " ${{env.hello}}deploying ..."